#!/usr/bin/env python3
"""Starlight Idea Swarm — local intake skeleton.

Writes a dated Idea card under docs/ideas/ and an optional GitHub issue body
stub under docs/ideas/_outbox/. No network calls. Safe under BOUNDED disk.

Usage:
  python scripts/idea_swarm_intake.py --text "Your idea..." --source hermes --tags "arcanea,product"
  python scripts/idea_swarm_intake.py --file path/to/note.md --source chatgpt-paste
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
IDEAS = ROOT / "docs" / "ideas"
OUTBOX = IDEAS / "_outbox"


def slugify(text: str, max_len: int = 48) -> str:
    s = text.strip().lower()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s).strip("-")
    return (s[:max_len] or "idea").rstrip("-")


def build_card(
    text: str,
    source: str,
    tags: list[str],
    idea_id: str,
    created: str,
) -> str:
    one_liner = text.strip().splitlines()[0][:160]
    tag_line = ", ".join(tags) if tags else "untagged"
    return f"""# Idea Card — {idea_id}

| Field | Value |
|-------|-------|
| id | `{idea_id}` |
| created | {created} |
| source | {source} |
| tags | {tag_line} |
| stage | capture |
| ship_bar | _pending quantify_ |
| critic | _pending debate_ |

## One-liner

{one_liner}

## Raw

{text.strip()}

## Provenance

- Intake: `scripts/idea_swarm_intake.py`
- Doctrine: `docs/IDEA-SWARM.md`
- Next: Cluster → Refine → Quantify → Debate (Planner/Executor/Critic) → Align (GitHub)

## Alignment stubs

- [ ] Map to portfolio repo / ROADMAP
- [ ] Open GitHub issue with label `idea-swarm`
- [ ] Link second-brain vault note if from export

## Debate receipt

```json
{{
  "ideaId": "{idea_id}",
  "stage": "capture",
  "critic": {{"verdict": "PENDING", "blockers": [], "score": null}}
}}
```
"""


def build_issue_body(idea_id: str, text: str, tags: list[str]) -> str:
    tag_line = ", ".join(f"`{t}`" for t in tags) if tags else "_none_"
    return f"""## Idea Swarm capture

**ID:** `{idea_id}`  
**Tags:** {tag_line}

### Summary

{text.strip()[:2000]}

### Done when

- [ ] Critic PASS on refine + quantify
- [ ] Linked to roadmap or explicit new goal
- [ ] Evidence path in queen report or vault

### Labels

`idea-swarm` · add `roadmap-align:<repo>` when known

---
_Generated by Starlight Idea Swarm intake. Not auto-filed until Critic PASS._
"""


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Starlight Idea Swarm intake")
    p.add_argument("--text", type=str, help="Raw idea text")
    p.add_argument("--file", type=str, help="Read idea text from file")
    p.add_argument("--source", type=str, default="hermes", help="Provenance source")
    p.add_argument("--tags", type=str, default="", help="Comma-separated tags")
    args = p.parse_args(argv)

    if args.file:
        text = Path(args.file).read_text(encoding="utf-8")
    elif args.text:
        text = args.text
    else:
        print("Provide --text or --file", file=sys.stderr)
        return 2

    text = text.strip()
    if not text:
        print("Empty idea text", file=sys.stderr)
        return 2

    tags = [t.strip() for t in args.tags.split(",") if t.strip()]
    now = datetime.now(timezone.utc)
    created = now.strftime("%Y-%m-%dT%H:%M:%SZ")
    day = now.strftime("%Y%m%d")
    idea_id = f"isw-{day}-{slugify(text)}"

    IDEAS.mkdir(parents=True, exist_ok=True)
    OUTBOX.mkdir(parents=True, exist_ok=True)

    card_path = IDEAS / f"{idea_id}.md"
    issue_path = OUTBOX / f"{idea_id}-github-issue.md"
    meta_path = OUTBOX / f"{idea_id}.json"

    card_path.write_text(build_card(text, args.source, tags, idea_id, created), encoding="utf-8")
    issue_path.write_text(build_issue_body(idea_id, text, tags), encoding="utf-8")
    meta_path.write_text(
        json.dumps(
            {
                "ideaId": idea_id,
                "created": created,
                "source": args.source,
                "tags": tags,
                "cardPath": str(card_path.relative_to(ROOT)).replace("\\", "/"),
                "issueBodyPath": str(issue_path.relative_to(ROOT)).replace("\\", "/"),
                "stage": "capture",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    print(f"ideaId={idea_id}")
    print(f"card={card_path}")
    print(f"issue_body={issue_path}")
    print(f"meta={meta_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
